addons:
  sonarqube: true
language: java
jdk:
  - oraclejdk8
env:
  NODE_VERSION="9.3.0"
  ANGULAR_CLI_VERSION="1.6.3"
  HEROKU_API_KEY="$HEROKU_API_KEY"
before_install:
  - nvm install $NODE_VERSION
  - npm install -g @angular/cli@$ANGULAR_CLI_VERSION
script:
  - mvn clean install
  - mvn -Pheroku
cache:
  directories:
    - "$HOME/.m2/repository"
