addons:
  sonarqube: true
language: java
jdk:
  - oraclejdk8
env:
  NODE_VERSION="9.3.0"
  ANGULAR_CLI_VERSION="1.6.3"
before_install:
  - nvm install $NODE_VERSION
  - npm install -g @angular/cli@$ANGULAR_CLI_VERSION
  - heroku plugins:install heroku-cli-deploy
script:
  - mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: yQrBpSjoEbQy2Hm4irCETAKMwJEuGpLVFU2f4UNoHYJEJvilvyuqoVnkWQsUkShLAn3bHtx8DXVwWQSYZGJbNXBIfwN++z9D9vAxV9QMQ59Uah6l+QtnsWvKLztghATD0xw5ziJICQ87BMb0FktKpDjxHdjKGXVKKwn3UKKXcoIvLE/Eb+X4aQ2+wmiMEFHnpQKRxTL/XM/pk1zemA4ThjmDmDqlaGJ4cenFzS5+/IeD4/2HlwgPv9by638auAibPhGGGbvr96jNHD5kM2a5sh3E9JDzzV6zHLd4DnKawu3yRPGk/y2Nhc16CxRTIgZ5cFN8nsg+g+4hHTgWLi2oxiNqu8PMPG2oMSVJ9nER4XG91ygbnF7HpHlEl5PXN79i2kNCZGYMoAEyJKXdK6QHBG6AyZnJTRZtEgPLrc0wzaf9klF22+34C5X+olmFtA8tdcdRIaTw3yx8R3e89pGhL90/Q+NuioIbjA9Tq3d2SlKaHpaTuA5SLFwMig1LN4uxhoW79Lhhd5FaPfLgKCzZjv1fk1Fn4lScS3+shT9ml1UUhaS1rWH1BL34Nn9QuLi5EclcVfiskrUgnueI7rSGQy3++8iw4u4SZcLjgup8ogqpe+FJj/Y66CJHiF/5oLVOUl5qEuuW/QxsMbeWksHlyECVtuJDkBjxSjpJ5kXhv4A=
  app: patiolegal
  skip_cleanup: true
cache:
  directories:
    - "$HOME/.m2/repository"
